  CREATE TABLE "C##ADMIN"."CLIENTES" 
   (	"DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"CELULAR" VARCHAR2(10 CHAR), 
	"DIRECCION" VARCHAR2(200 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"PRIMER_APELLIDO" VARCHAR2(30 CHAR), 
	"PRIMER_NOMBRE" VARCHAR2(30 CHAR), 
	"SEGUNDO_APELLIDO" VARCHAR2(30 CHAR), 
	"SEGUNDO_NOMBRE" VARCHAR2(30 CHAR), 
	 PRIMARY KEY ("DOCUMENTO", "TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."FOTOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_MANTENIMIENTO" NUMBER(10,0), 
	"RUTA" VARCHAR2(200 CHAR), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."MARCAS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE_MARCA" VARCHAR2(30 CHAR), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."MECANICOS" 
   (	"DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"CELULAR" VARCHAR2(10 CHAR), 
	"ESTADO" CHAR(1 CHAR), 
	"PRIMER_APELLIDO" VARCHAR2(30 CHAR), 
	"PRIMER_NOMBRE" VARCHAR2(30 CHAR), 
	"SEGUNDO_APELLIDO" VARCHAR2(30 CHAR), 
	"SEGUNDO_NOMBRE" VARCHAR2(30 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"DIRECCION" VARCHAR2(200 CHAR), 
	 PRIMARY KEY ("DOCUMENTO", "TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."REPUESTOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE_REPUESTO" VARCHAR2(100 CHAR), 
	"PRECIO_UNITARIO" NUMBER(10,0), 
	"PROVEDOR" VARCHAR2(300 CHAR), 
	"UNIDADES_INVENTARIO" NUMBER(10,0), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."SERVICIOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE_SERVICIO" VARCHAR2(100 CHAR), 
	"PRECIO" NUMBER(10,0), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

 CREATE TABLE "C##ADMIN"."VEHICULOS" 
   (	"PLACA" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLOR" VARCHAR2(30 CHAR), 
	"CLI_DOCUMENTO" NUMBER(10,0), 
	"CLI_TIPO_DOCUMENTO" VARCHAR2(2 CHAR), 
	"COD_MARCA" NUMBER(10,0), 
	 PRIMARY KEY ("PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK3MPAOB22S9SWM7XHDHGSCWSIR" FOREIGN KEY ("CLI_DOCUMENTO", "CLI_TIPO_DOCUMENTO")
	  REFERENCES "C##ADMIN"."CLIENTES" ("DOCUMENTO", "TIPO_DOCUMENTO") ENABLE, 
	 CONSTRAINT "FKD7Q0YGJLX3UE73YIAT7DXNBF3" FOREIGN KEY ("COD_MARCA")
	  REFERENCES "C##ADMIN"."MARCAS" ("CODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "C##ADMIN"."MANTENIMIENTOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ESTADO" NUMBER(10,0), 
	"FECHA" DATE, 
	"MEC_DOCUMENTO" NUMBER(10,0), 
	"MEC_TIPO_DOCUMENTO" VARCHAR2(2 CHAR), 
	"COD_PLACA" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKE403K4X51BGM4N72YCMNAG7OH" FOREIGN KEY ("MEC_DOCUMENTO", "MEC_TIPO_DOCUMENTO")
	  REFERENCES "C##ADMIN"."MECANICOS" ("DOCUMENTO", "TIPO_DOCUMENTO") ENABLE, 
	 CONSTRAINT "FKRNT69KJR4AW1N4BSIBC2EPPMH" FOREIGN KEY ("COD_PLACA")
	  REFERENCES "C##ADMIN"."VEHICULOS" ("PLACA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "C##ADMIN"."REPUESTOS_X_MANTENIMIENTOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIEMPO_ESTIMADO" NUMBER(10,0), 
	"UNIDADES" NUMBER(10,0), 
	"COD_MANTENIMIENTO" NUMBER(10,0), 
	"COD_REPUESTO" NUMBER(10,0), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKRNWF70S57QVOSPUMRXTDYNGHA" FOREIGN KEY ("COD_MANTENIMIENTO")
	  REFERENCES "C##ADMIN"."MANTENIMIENTOS" ("CODIGO") ENABLE, 
	 CONSTRAINT "FK4MXB3PMA4WRW0AH7P8TTOVVX0" FOREIGN KEY ("COD_REPUESTO")
	  REFERENCES "C##ADMIN"."REPUESTOS" ("CODIGO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE TABLE "C##ADMIN"."SERVICIOS_X_MANTENIMIENTOS" 
   (	"CODIGO" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIEMPO_ESTIMADO" NUMBER(10,0), 
	"COD_MANTENIMIENTO" NUMBER(10,0), 
	"COD_SERVICIO" NUMBER(10,0), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKILLQ2FDX11RL99H2YGKAJK78A" FOREIGN KEY ("COD_MANTENIMIENTO")
	  REFERENCES "C##ADMIN"."MANTENIMIENTOS" ("CODIGO") ENABLE, 
	 CONSTRAINT "FKH6U02W7C8S950OXST2HUX4FGT" FOREIGN KEY ("COD_SERVICIO")
	  REFERENCES "C##ADMIN"."SERVICIOS" ("CODIGO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;





 TABLE REPUESTOS_X_MANTENIMINETOS 
ADD CONSTRAINT REP_XMAN_REP_FK
FOREIGN KEY (COD_REPUESTO) REFERENCES REPUESTOS(CODIGO);

ALTER TABLE REPUESTOS_X_MANTENIMINETOS 
ADD CONSTRAINT REP_X_MTOS_MAN_FK
FOREIGN KEY (COD_MANTENIMIENTO) REFERENCES MANTENIMIENTOS(CODIGO);

ALTER TABLE FOTOS 
ADD CONSTRAINT FOTOS_MAN_FK
FOREIGN KEY (COD_MANTENIMIENTO) REFERENCES MANTENIMIENTOS(CODIGO);

ALTER TABLE MANTENIMIENTOS 
ADD CONSTRAINT MANTENIMINETOS_MECANICOS_FK
FOREIGN KEY (MEC_DOCUMENTO,MEC_TIPO_DOCUMENTO) REFERENCES MECANICOS(DOCUMENTO,TIPO_DOCUMENTO);

ALTER TABLE SERVICIOS_X_MANTENIMIENTOS 
ADD CONSTRAINT SER_X_MAN_SER_FK
FOREIGN KEY (COD_SERVICIO) REFERENCES SERVICIOS(CODIGO);

ALTER TABLE SERVICIOS_X_MANTENIMIENTOS 
ADD CONSTRAINT SER_X_MAN_MAN_FK
FOREIGN KEY (COD_MANTENIMIENTO) REFERENCES MANTENIMIENTOS(CODIGO);

ALTER TABLE VEHICULOS 
ADD CONSTRAINT VEHICULOS_CLIENTES_FK
FOREIGN KEY (CLI_DOCUMENTO,CLI_TIPO_DOCUMENTO) REFERENCES CLIENTES(DOCUMENTO,TIPO_DOCUMENTO);

ALTER TABLE VEHICULOS 
ADD CONSTRAINT VEHICULOS_MARCA_FK
FOREIGN KEY (COD_MARCA) REFERENCES MARCAS(CODIGO);


create or replace procedure C##ADMIN.INSERT_MECANICOS
  (I_TIPO_DOCUMENTO in VARCHAR2, I_DOCUMENTO NUMBER, I_PRIMER_NOMBRE in VARCHAR2, I_SEGUNDO_NOMBRE in VARCHAR2, 
  I_PRIMER_APELLIDO in VARCHAR2, I_SEGUNDO_APELLIDO in VARCHAR2, I_CELULAR in VARCHAR2, I_DIRECCION in VARCHAR2, 
  I_EMAIL in VARCHAR2, I_ESTADO CHAR,
  S_EXITO OUT NUMBER, S_MENSAJE OUT VARCHAR2)
 as
 begin
     INSERT INTO "C##ADMIN"."MECANICOS" (TIPO_DOCUMENTO, DOCUMENTO, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
     PRIMER_APELLIDO, SEGUNDO_APELLIDO, CELULAR, DIRECCION, EMAIL, ESTADO) 
     VALUES 
    (I_TIPO_DOCUMENTO, I_DOCUMENTO, I_PRIMER_NOMBRE, I_SEGUNDO_NOMBRE, 
    I_PRIMER_APELLIDO, I_SEGUNDO_APELLIDO, I_CELULAR, I_DIRECCION, I_EMAIL, I_ESTADO);
    
    S_EXITO := 0;
    S_MENSAJE := 'TRANSACCION EXITOSA';
    
    EXCEPTION
    WHEN others  THEN
      DBMS_OUTPUT.PUT_LINE('INSERCIÓN FALLIDA.');
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
      S_EXITO := 1;
      S_MENSAJE := 'INSERCIÓN FALLIDA. ' + SQLERRM;
  
  
 end;


create view v_prioridad_mecanicos as
select a.documento, a.primer_nombre, a.segundo_nombre, a.primer_apellido, a.segundo_apellido, nvl(b.estado,3) estado, count(*) as cantidad
from mecanicos a LEFT JOIN mantenimientos b on (a.documento = b.mec_documento) and (a.tipo_documento = b.mec_tipo_documento)
where a.estado <> 1 and nvl(b.estado,3) <> 1 and nvl(b.fecha, sysdate) > (sysdate - 30)
group by a.documento, a.primer_nombre, a.segundo_nombre, a.primer_apellido, a.segundo_apellido, 
nvl(b.estado,3) order by cantidad asc, estado desc;

